import type { Personality } from './types';

// The spider's phrase cupboard. Keep controls literal and dock phrases short.
// Plain text only: consumers use textContent, never interpret these as HTML.
export const copy = {
  intro: 'Eight legs. One brain cell. A magnificent sense of occasion.',
  temperamentHelp: 'choose your tiny menace',
  gentleEnd: 'tea with the aunties',
  wildEnd: 'confetti incident',
  pointerHelp: 'Hover to nominate a nibble. Page edges scroll.',
  touchHelp: 'No pointer? Your spider forages solo. Cursor guide needs a mouse or trackpad.',
  restoreHelp: 'Restore / Esc sends your guest home and removes its effects.',
  inactive: 'No visitor. A vacancy for one tiny menace. Summon when you’re ready.',
  paused: 'Paused. Eight feet up. Your trail stays here. Resume any time.',
  reducedMotion: 'Reduced motion: eight legs tucked in. Quiet company, no new strikes.',
  limit: 'The scrapbook is full. Restore for a fresh start.',
  exploring: 'Active · Exploring. Inspecting the buffet. Follow my cursor lets you guide.',
  following: 'Active · Hover chooses the next nibble. Edges scroll. Compliments to the cursor.',
  touch: 'Active · Exploring. A self-guided snack tour. Cursor guide needs a pointer.',
  summon: 'Summon your spider',
  summoned: 'Your tiny menace is here',
  pause: 'Pause',
  resume: 'Resume',
  restore: 'Restore',
  restoreTitle: 'Send the visitor home and remove its effects; keep your page edits',
  hintPointer: 'Enable Follow my cursor, then hover to nominate a nibble.',
  hintTouch: 'Your spider forages on its own. Pause keeps all eight feet still.',
  dismissHint: 'Mind the crumbs',
  unavailable:
    'This page is off limits or unavailable. Even tiny menaces need permission. Try a regular website or the playground.',
  failed:
    'Your spider could not start or respond. A small tangle in the silk. Reload this page, then try Summon again.',
  noTab: 'No available tab for these eight feet. Open a regular website or the playground.',
} as const;

export const spiderTypes: Record<Personality, { name: string; cue: string; description: string }> =
  {
    curious: {
      name: 'Widow',
      cue: '✦',
      description: 'Long legs. Tiny detective. Every precise little bite is strictly for research.',
    },
    dreamy: {
      name: 'Orb-weaver',
      cue: '☾',
      description:
        'Round as a moon. Peels gently, wanders slowly, thinks the margins are a meadow.',
    },
    feral: {
      name: 'Jumping spider',
      cue: '↯',
      description: 'Big eyes. Spring-loaded opinions. Pounces first, shreds the paperwork later.',
    },
  };

export const intensityWords = ['Dainty nibbles', 'Licensed mischief', 'Confetti goblin'] as const;
type Phrases = readonly [string, ...string[]];
export const activities = {
  arrive: [
    'descending by silk elevator…',
    'special delivery: eight feet…',
    'a guest drops in…',
    'lowering the tiny chandelier…',
    'arriving on a thread of hope…',
    'one moment, unfolding the legs…',
    'the ceiling sent a friend…',
    'checking in, luggage is legs…',
    'a very small entrance…',
    'hello below, mind the silk…',
  ],
  recover: [
    'untangling the landing gear…',
    'recounting all eight feet…',
    'pardon the wobble…',
    'locating the floor again…',
    'putting the knees in order…',
    'a brief committee of ankles…',
    'righting the tiny ship…',
    'retrieving a misplaced poise…',
    'that was nearly graceful…',
    'reassembling the dignity…',
  ],
  notice: [
    'a suspiciously delicious detail…',
    'oh? a morsel?',
    'the plot has crumbs…',
    'a little something over there…',
    'did that comma wink?',
    'a glimmer in the nibble zone…',
    'well, look at this curio…',
    'the whiskers have questions…',
    'a promising speck of nonsense…',
    'someone left a lovely scrap…',
  ],
  investigate: [
    'sniffing the fine print…',
    'checking for footnotes…',
    'a closer look, for science…',
    'reading between the crumbs…',
    'poking at the possibilities…',
    'consulting the front feet…',
    'examining the snack credentials…',
    'squinting with extra eyes…',
    'circling a tiny mystery…',
    'taking a scholarly sniff…',
  ],
  lock: [
    'this one looks bite-sized',
    'a nibble has been nominated',
    'yes, this little delicacy',
    'the feet have reached consensus',
    'a morsel of some importance',
    'this bit has excellent vibes',
    'one tiny reservation confirmed',
    'a most compelling crumb',
    'the nibble committee approves',
    'a little X marks the snack',
  ],
  settle: [
    'letting the confetti land…',
    'admiring the handiwork…',
    'waiting for the crumbs to settle…',
    'a moment for the little mess…',
    'surveying the nibble aftermath…',
    'allowing the drama to subside…',
    'quite pleased with those crumbs…',
    'giving the scraps some space…',
    'a tiny bow seems appropriate…',
    'letting gravity do the filing…',
  ],
} as const satisfies Record<string, Phrases>;
export const temperamentActivities = {
  curious: {
    scan: [
      'auditing the crumbs',
      'on footnote patrol',
      'collecting tiny suspicions',
      'following a paper trail',
      'seeking a second opinion',
      'browsing the evidence buffet',
      'undercover in the margins',
      'a small inquiry on eight feet',
      'looking for loose conclusions',
      'cataloguing possible nibbles',
    ],
    prepare: [
      'adjusting the tiny spectacles…',
      'one careful nibble, for science…',
      'measuring twice, biting once…',
      'sharpening a small hypothesis…',
      'putting on imaginary gloves…',
      'clearing a space in the notebook…',
      'calibrating the front toes…',
      'checking the nibble protocol…',
      'a delicate experiment awaits…',
      'lining up the little questions…',
    ],
    strike: [
      'conducting nibble research…',
      'taking a very small sample…',
      'opening a crumb investigation…',
      'testing a bite-sized theory…',
      'extracting one tiny finding…',
      'collecting edible evidence…',
      'gently cross-examining a scrap…',
      'making a hole in the argument…',
      'putting curiosity into practice…',
      'taking notes with the front feet…',
    ],
  },
  dreamy: {
    scan: [
      'grazing in the margins',
      'following a daydream',
      'looking for moon crumbs',
      'wandering through a maybe',
      'taking the scenic sentence',
      'listening for sleepy commas',
      'on a very small ramble',
      'drifting toward something nice',
      'counting imaginary dewdrops',
      'lost in a lovely paragraph',
    ],
    prepare: [
      'asking the morsel nicely…',
      'a little stretch before the nibble…',
      'unfolding a small daydream…',
      'taking a breath of moonlight…',
      'tucking a cloud behind one ear…',
      'warming the delicate toes…',
      'making room for a little lovely…',
      'waiting for the perfect hush…',
      'straightening a petal napkin…',
      'a soft thought takes shape…',
    ],
    strike: [
      'peeling a little daydream…',
      'loosening a moonlit morsel…',
      'borrowing a scrap of lovely…',
      'lifting the corner of a wish…',
      'gathering a pocketful of hush…',
      'unwrapping a tiny reverie…',
      'plucking a petal of nonsense…',
      'coaxing a crumb into the breeze…',
      'taking a sip of the scenery…',
      'making a little room for wonder…',
    ],
  },
  feral: {
    scan: [
      'scouting the snack frontier',
      'unsupervised, naturally',
      'plotting a confetti incident',
      'looking for a bad little idea',
      'patrolling without a permit',
      'all eyes, no indoor voice',
      'following the smell of chaos',
      'a picnic with consequences',
      'shopping for trouble scraps',
      'seeking a worthy kerfuffle',
    ],
    prepare: [
      'winding up the nonsense…',
      'folding away the table manners…',
      'loading the springy opinions…',
      'tightening the chaos springs…',
      'briefly considering manners…',
      'revving the tiny knees…',
      'preparing an unsolicited remix…',
      'putting reason in a drawer…',
      'a terrible idea gets its shoes…',
      'crouching toward a kerfuffle…',
    ],
    strike: [
      'releasing the confetti goblin…',
      'making extremely small trouble…',
      'filing a shredded complaint…',
      'applying a vigorous opinion…',
      'turning decorum into confetti…',
      'conducting a tiny snack raid…',
      'putting the rip in manuscript…',
      'performing unlicensed collage…',
      'starting a pocket-sized ruckus…',
      'a very local crumb emergency…',
    ],
  },
} as const satisfies Record<Personality, Record<'scan' | 'prepare' | 'strike', Phrases>>;

export const dockCopy = {
  limit: 'marks · scrapbook full · Restore to explore again',
  paused: 'marks · paused · eight feet up',
  quiet: 'quiet company · toes tucked in',
  unavailable: 'quiet visitor · highlights unavailable',
  edge: 'edge expedition · move inward to stop',
  following: 'marks · hover to nominate a nibble',
} as const;
